#!/bin/bash

#ERSTE SCHRITTE
  #Autorisiere Zugriff auf Geräte-Speicher
  termux-setup-storage

  #Install Git
  pkg install git gh -y

  #Install Repos
  pkg install root-repo x11-repo -y

  #Install Hilfe & Info
  pkg install man mandoc hwinfo -y

  #Install Network
  pkg install nmap tcpdump -y

  #Install Weiteres
  pkg install tree wget curl -y

